### ISSUE TITLE
Console error misleading when a resolver does not have a return statement.

### ISSUE THREAD

**Issue by freakpol** [daniel-duarte/flowed#19]
When a resolver does not have a return `statement`, the following error appears in console, misleading on the proper way to solve the issue:

```
(node:56642) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at Task.mapResultsFromResolver (/.../node_modules/flowed/dist/engine/task.js:113:31)
    at /.../node_modules/flowed/dist/engine/task.js:57:38
```

**Comment by daniel-duarte** [comment]
Thanks for reporting @freakpol, will take a look.

**Comment by daniel-duarte** [comment]
Solved. To be included in next release.
Now when a resolver returns an incorrect value, a Promise that resolves to an incorrect value or even doesn't  return at all, the following error will be thrown:
 
`"Expected resolver for task '<<your task name>>' to return an object or Promise that resolves to object. Returned value is of type '<<type returned>>'."`
