### ISSUE TITLE
Transform feature does not support "let"

### ISSUE THREAD

**Issue by freakpol** [daniel-duarte/flowed#22]
Latest version of https://selecttransform.github.io/site/ offers support for "let" allowing to create local variables for the templates. Seems that the version on flowed is not updated to use such feature.
Would you consider adding it?

**Comment by daniel-duarte** [comment]
Thanks @freakpol. I'll check the latest available features in ST to consider adding them.

**Comment by daniel-duarte** [comment]
Added and released in version 1.7.1.
